In [2]:
import numpy as np

a=np.array([1,2,3])
print(a.shape)

(3,)


In [3]:
b=np.array([1,2,3],[4,5,6])
print(b.shape)

TypeError: data type not understood

In [6]:
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)

(2, 3)


In [7]:
print(b[0,0])

1


In [8]:
print(b[1,1])

5


In [9]:
e=np.random.random((2,2))
print(e)

[[0.71591689 0.43899848]
 [0.48333728 0.17705342]]


In [10]:
e=np.random.random((2,2))
print(e)

[[0.67793875 0.82858258]
 [0.99386361 0.81084754]]


In [11]:
c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(c.shape)

(3, 4)


In [12]:
b=a[:2,1:3]

IndexError: too many indices for array

In [16]:
d=c[:2, 1:3]
print (d)

[[2 3]
 [6 7]]


In [18]:
row_r1 = c[1, : ]
print (row_r1, row_r1.shape)

[5 6 7 8] (4,)


In [19]:
row_r1 = c[1, 1:2 ]
print (row_r1, row_r1.shape)

[6] (1,)


In [20]:
row_r1 = c[1:2, : ]
print (row_r1, row_r1.shape)

[[5 6 7 8]] (1, 4)


In [24]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b=np.array([0,2,0,1])
print(a[np.arange(4),b]+= 10)

SyntaxError: invalid syntax (<ipython-input-24-e185ca336718>, line 3)

In [25]:
a[np.arange(4),b]+= 10


In [26]:
print a

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(a)? (<ipython-input-26-da1608c9d425>, line 1)

In [27]:
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [29]:
bool_idx = (a>5)
print(a[bool_idx])

[11 16 17  8  9 10 21 12]


In [31]:
x=np.array([1,2], dtype=np.float64)
print(x)

[1. 2.]


In [45]:
x=np.array([[1,2],[3,4]], dtype=np.float64)
y=np.array([[5,6],[7,8]], dtype=np.float64)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]


In [47]:
x=np.array([[[1,2,1],[2,3,2]],[[3,4,3],[4,5,4]]])
print(x.T.shape)

(3, 2, 2)


In [44]:
print(x.shape)

(2, 2, 3)


In [48]:
x=np.array([[1,2,1],[2,3,2],[3,4,3],[4,5,4]])
v=np.array([1,1,1])
vv=np.tile(v,(4,1))
print(x+vv)

[[2 3 2]
 [3 4 3]
 [4 5 4]
 [5 6 5]]


In [49]:
print(x+v)

[[2 3 2]
 [3 4 3]
 [4 5 4]
 [5 6 5]]


In [50]:
v=np.array([1,1,1,0])
print(x+v)


ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [52]:
v=np.array([2])
print(x+v)

[[3 4 3]
 [4 5 4]
 [5 6 5]
 [6 7 6]]


In [55]:
v=np.array([[1,2],[2,3]])
w=np.array([4,5])
print(v*w)

[[ 4 10]
 [ 8 15]]


In [10]:
import pandas as pd
df=pd.read_csv("/Users/karthickrajamani/Desktop/adult.csv", header=None)
df.columns('age', 'workclass','fnlwgt','educ','educ-num','marital','occupation','relation','race','sex','capital-gain','capital-loss','hours','native','class')
df.head(5)

TypeError: 'Int64Index' object is not callable